/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui;




import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;

/**
 *
 * @author Franz
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private void close(){
        WindowEvent closeWindow = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
        
    
    }
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        personal = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        antrag = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lohn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dash = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        antraege = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lohnGehalt = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        personalakten = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        openLabel = new javax.swing.JLabel();

        jButton1.setText("Abmelden");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(220, 220, 220));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personalakten", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Akte 1  ", "Akte 2", "Akte 3", "Akte 4", "Akte 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Personalakte erstellen");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Personalakte erstellen");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(10000), "Mustermann", "Max", "Musterberuf"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Vorname", "Berufsbezeichnung"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout personalLayout = new javax.swing.GroupLayout(personal);
        personal.setLayout(personalLayout);
        personalLayout.setHorizontalGroup(
            personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jButton5)
                .addContainerGap(381, Short.MAX_VALUE))
            .addGroup(personalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        personalLayout.setVerticalGroup(
            personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("tab2", personal);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Anträge");

        javax.swing.GroupLayout antragLayout = new javax.swing.GroupLayout(antrag);
        antrag.setLayout(antragLayout);
        antragLayout.setHorizontalGroup(
            antragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(antragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(antragLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        antragLayout.setVerticalGroup(
            antragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(antragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(antragLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab3", antrag);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Lohn");

        javax.swing.GroupLayout lohnLayout = new javax.swing.GroupLayout(lohn);
        lohn.setLayout(lohnLayout);
        lohnLayout.setHorizontalGroup(
            lohnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(lohnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lohnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        lohnLayout.setVerticalGroup(
            lohnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(lohnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lohnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab4", lohn);

        dash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Dashboard");
        dash.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jTabbedPane1.addTab("tab1", dash);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -25, 840, 665));

        jPanel2.setBackground(new java.awt.Color(5, 10, 48));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setBackground(new java.awt.Color(255, 255, 255));
        closeLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        closeLabel.setText("❌\t");
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        jPanel2.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 30, 30));

        jPanel4.setBackground(new java.awt.Color(54, 70, 78));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        antraege.setBackground(new java.awt.Color(54, 70, 78));
        antraege.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        antraege.setForeground(new java.awt.Color(255, 255, 255));
        antraege.setText("        Anträge");
        antraege.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        antraege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                antraegeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                antraegeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                antraegeMouseExited(evt);
            }
        });
        jPanel4.add(antraege, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 40));

        jPanel5.setBackground(new java.awt.Color(54, 70, 78));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lohnGehalt.setBackground(new java.awt.Color(54, 70, 78));
        lohnGehalt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lohnGehalt.setForeground(new java.awt.Color(255, 255, 255));
        lohnGehalt.setText("        Lohn und Gehalt");
        lohnGehalt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lohnGehaltMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lohnGehaltMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lohnGehaltMouseExited(evt);
            }
        });
        jPanel5.add(lohnGehalt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 40));

        jPanel6.setBackground(new java.awt.Color(54, 70, 78));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personalakten.setBackground(new java.awt.Color(54, 70, 78));
        personalakten.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        personalakten.setForeground(new java.awt.Color(255, 255, 255));
        personalakten.setText("        Personalakten");
        personalakten.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        personalakten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personalaktenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                personalaktenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                personalaktenMouseExited(evt);
            }
        });
        jPanel6.add(personalakten, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 40));

        jPanel7.setBackground(new java.awt.Color(54, 70, 78));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard.setBackground(new java.awt.Color(54, 70, 78));
        dashboard.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("        Dashboard");
        dashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
        });
        jPanel7.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Abmelden");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 640));

        openLabel.setBackground(new java.awt.Color(255, 255, 255));
        openLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        openLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        openLabel.setText("≡");
        openLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        openLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openLabelMouseClicked(evt);
            }
        });
        jPanel1.add(openLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Personalakte_erstellen pa_e = new Personalakte_erstellen();
        pa_e.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    int x = 210; 
    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        if(x==210){
            jPanel2.setSize(210,640);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i =210;i>=0;i--){
                            Thread.sleep(1);
                            jPanel2.setSize(i,640);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
            };th.start();
            x=0;
        }
    }//GEN-LAST:event_closeLabelMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        close();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void personalaktenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personalaktenMouseClicked

        //jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.setSelectedComponent(personal);
                
    }//GEN-LAST:event_personalaktenMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        
        //jTabbedPane1.setSelectedIndex(1);
        jTabbedPane1.setSelectedComponent(dash);
        
    }//GEN-LAST:event_dashboardMouseClicked

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        
        dashboard.setBorder(new BevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        dashboard.setBorder(new BevelBorder(BevelBorder.LOWERED));
    }//GEN-LAST:event_dashboardMouseExited

    private void personalaktenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personalaktenMouseEntered
        personalakten.setBorder(new BevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_personalaktenMouseEntered

    private void personalaktenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personalaktenMouseExited
        personalakten.setBorder(new BevelBorder(BevelBorder.LOWERED));
    }//GEN-LAST:event_personalaktenMouseExited

    private void antraegeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antraegeMouseEntered
        antraege.setBorder(new BevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_antraegeMouseEntered

    private void antraegeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antraegeMouseExited
        antraege.setBorder(new BevelBorder(BevelBorder.LOWERED));
    }//GEN-LAST:event_antraegeMouseExited

    private void lohnGehaltMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lohnGehaltMouseEntered
        lohnGehalt.setBorder(new BevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_lohnGehaltMouseEntered

    private void lohnGehaltMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lohnGehaltMouseExited
        lohnGehalt.setBorder(new BevelBorder(BevelBorder.LOWERED));
    }//GEN-LAST:event_lohnGehaltMouseExited

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        Personalakte_erstellen pa_e = new Personalakte_erstellen();
        pa_e.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        Personalakte_erstellen pa_e = new Personalakte_erstellen();
        pa_e.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void antraegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antraegeMouseClicked
        
        //jTabbedPane1.setSelectedIndex(2);
        jTabbedPane1.setSelectedComponent(antrag);
    }//GEN-LAST:event_antraegeMouseClicked

    private void lohnGehaltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lohnGehaltMouseClicked
        
        //jTabbedPane1.setSelectedIndex(3);
        jTabbedPane1.setSelectedComponent(lohn);
        
    }//GEN-LAST:event_lohnGehaltMouseClicked

    private void openLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openLabelMouseClicked
        if(x==0){
            jPanel2.show();
            jPanel2.setSize(210,640);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i =0;i<=x;i++){
                            Thread.sleep(1);
                            jPanel2.setSize(i,640);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
            };th.start();
            x=210;
        }
    }//GEN-LAST:event_openLabelMouseClicked
     
    
     
                       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel antraege;
    private javax.swing.JPanel antrag;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JPanel dash;
    private javax.swing.JLabel dashboard;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel lohn;
    private javax.swing.JLabel lohnGehalt;
    private javax.swing.JLabel openLabel;
    private javax.swing.JPanel personal;
    private javax.swing.JLabel personalakten;
    // End of variables declaration//GEN-END:variables
}
