package GUI;



import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Franz
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private void close(){
        WindowEvent closeWindow = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPANEL = new javax.swing.JPanel();
        nutzernameLABEL = new javax.swing.JLabel();
        nutzernameFIELD = new javax.swing.JTextField();
        passwortLABEL = new javax.swing.JLabel();
        passwortFIELD = new javax.swing.JPasswordField();
        loginBUTTON = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AMGIS | Personalverwaltung");

        loginPANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N


        nutzernameLABEL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nutzernameLABEL.setText("Kontoname:");
        loginPANEL.add(nutzernameLABEL);
        nutzernameLABEL.setSize(10,30);


        nutzernameFIELD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nutzernameFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutzernameFIELDActionPerformed(evt);
            }
        });
        loginPANEL.add(nutzernameFIELD);
        nutzernameFIELD.setSize(95,28);


        passwortLABEL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwortLABEL.setText("Passwort:");
        //loginPANEL.add(passwortLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 75, -1, -1));

        passwortFIELD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwortFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwortFIELDActionPerformed(evt);
            }
        });
        loginPANEL.add(passwortFIELD);
        passwortFIELD.setSize(29,75);

        loginBUTTON.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginBUTTON.setText("Login");
        loginBUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBUTTONMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBUTTONMousePressed(evt);
            }
        });
        loginBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBUTTONActionPerformed(evt);
            }
        });
        loginPANEL.add(loginBUTTON);



        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Hilfe");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginPANEL.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(loginPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(loginPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nutzernameFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutzernameFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nutzernameFIELDActionPerformed

    private void passwortFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwortFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwortFIELDActionPerformed

    private void loginBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBUTTONActionPerformed
        // TODO add your handling code here:
        close();
        //Main m = new Main();
        //m.setVisible(true);
        //Main.setVisible(true);
    }//GEN-LAST:event_loginBUTTONActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loginBUTTONMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBUTTONMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBUTTONMousePressed

    private void loginBUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBUTTONMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBUTTONMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton loginBUTTON;
    private javax.swing.JPanel loginPANEL;
    private javax.swing.JTextField nutzernameFIELD;
    private javax.swing.JLabel nutzernameLABEL;
    private javax.swing.JPasswordField passwortFIELD;
    private javax.swing.JLabel passwortLABEL;
    // End of variables declaration//GEN-END:variables
}

